name: ssdlc-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      VERSION: 1.0.2

    steps:
    - uses: actions/checkout@v4

    - name: Extract short commit hash
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.library.tamu.edu/utilities/port-context-path-tester:${{ env.VERSION }}-${{ env.SHORT_SHA }}

    - name: Verify image is built with correct tag
      run: docker images
