name: ssdlc-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      VERSION: 1.0.2

    steps:
    - uses: actions/checkout@v4

    - name: Extract short commit hash
      id: vars
      run: echo "::set-output name=short_sha::${GITHUB_SHA::7}"
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag harbor.library.tamu.edu/utilities/port-context-path-tester:${{ env.VERSION }}-${{ steps.vars.outputs.short_sha }}
